set(CONFIGURATION ${CMAKE_BUILD_TYPE})

file(COPY ${CMAKE_CURRENT_LIST_DIR}/assets DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/${CONFIGURATION}")
file(COPY ${CMAKE_CURRENT_LIST_DIR}/data DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/${CONFIGURATION}")