# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  release:
    types: [created]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Download git submodules
        run: git submodule update --init --recursive

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B ./cmake-build-release

      - name: Build
        run: cmake --build ./cmake-build-debug --target Dungeon -- -DCMAKE_BUILD_TYPE=Release -j 14

      - name: Prepare artifacts
        run: |
          mkdir build
          cp ./cmake-build-release/Release artifacts/
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Dungeon-${{ runner.os }}
          path: artifacts/*
  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: Dungeon-*/**
          token: '${{ github.token }}'